//
// Created by Matthew Tapia on 12/11/22.
//

#ifndef PORTFOLIO_IMAGESENUM_H
#define PORTFOLIO_IMAGESENUM_H

enum ImagesEnum{
    CLUB,
    DIAMOND,
    HEART,
    SPADE,
    GREEN_BALL_THUMBNAIL,
    BOUNCING_BALL_THUMBNAIL,
    PONG_THUMBNAIL,
    TOPHATGUY_THUMBNAIL,
    CARD_THUMBNAIL,
    POKER_THUMBNAIL,
    C4_THUMBNAIL,
    LAST_IMAGE
};

#endif //PORTFOLIO_IMAGESENUM_H
