//
// Created by Matthew Tapia on 10/29/22.
//

#ifndef POKER_ANALYSIS_RANKENUM_H
#define POKER_ANALYSIS_RANKENUM_H

enum RankEnum{ACE, TWO, THREE, FOUR, FIVE, SIX, SEVEN, EIGHT, NINE, TEN, JACK, QUEEN, KING, END_RANK};

#endif //POKER_ANALYSIS_RANKENUM_H
