//
// Created by Matthew Tapia on 10/29/22.
//

#ifndef POKER_ANALYSIS_SUITENUM_H
#define POKER_ANALYSIS_SUITENUM_H

enum SuitEnum{HEARTS, DIAMONDS, CLUBS, SPADES, END_SUIT};

#endif //POKER_ANALYSIS_SUITENUM_H
